services:
    taxer:
        image: taxer
        container_name: taxer
        restart: unless-stopped
        pull_policy: never
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - <YT-DLP-PATH>:/usr/local/bin/yt-dlp
            - <FFMPEG-PATH>:/usr/local/bin/ffmpeg
        environment:
            DISCORD_TOKEN:

            YT_DLP_PATH: /usr/local/bin/yt-dlp
            FFMPEG_PATH: /usr/local/bin/ffmpeg
